// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAudd62x0QGShZhA1CO61jTVL7dcgm80Jw',
    appId: '1:1076866777824:web:fa393d148fb0bf9614c685',
    messagingSenderId: '1076866777824',
    projectId: 'contact-trace-2025',
    authDomain: 'contact-trace-2025.firebaseapp.com',
    storageBucket: 'contact-trace-2025.firebasestorage.app',
    measurementId: 'G-VCVHE9NBK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4qkmqDics7vONCl20l2nDP1w7cowTzBo',
    appId: '1:1076866777824:android:4f6557915da4241c14c685',
    messagingSenderId: '1076866777824',
    projectId: 'contact-trace-2025',
    storageBucket: 'contact-trace-2025.firebasestorage.app',
  );
}
